### ISSUE TITLE
footer merged but it doesn't stick the bottom of the page

### ISSUE THREAD

**Issue by Guillaumejfrt** [Guillaumejfrt/ticktock_app#10]
@cherineelf @Philthestyle 
on n'a mergé le footer trop vite. Il ne colle pas au bas de la page. 
Pouvez-vous mettre une copie écran de réalisation comme ça on valide plus facilement ce genre de petit bug? 

@cherineelf peux-tu corriger le bug sur une nouvelle branch et la repusher?

Merci mes haricots.

![screen shot 2017-05-13 at 11 15 03](https://cloud.githubusercontent.com/assets/24220655/26024357/ed2abbe6-37cf-11e7-8f87-6bd4b3a181e5.png)

**Comment by Guillaumejfrt** [comment]
ok ça ne se voit pas très sur ma photo mais allez voir en prod, vous verrez mieux.

**Comment by cherineelf** [comment]
Tu as eu mon dernier message ? On en a parlé à Arnaud hier soir et il nous a dit que c'était normal dans la mesure où on a encore rien mis en contenu de page.

**Comment by Guillaumejfrt** [comment]
yes ok! merci
